export const SET_USER_ID = 'SET_USER_ID';
export const SYNC_IDM_REQUEST = 'SYNC_IDM_REQUEST';
export const SYNC_IDM_SUCCESS = 'SYNC_IDM_SUCCESS';
export const SYNC_IDM_FAILURE = 'SYNC_IDM_FAILURE';

export const FETCH_PIS_REQUEST = 'FETCH_PIS_REQUEST';
export const FETCH_PIS_SUCCESS = 'FETCH_PIS_SUCCESS';
export const FETCH_PIS_FAILURE = 'FETCH_PIS_FAILURE';